/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ComplianceModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addComplianceOfficer"
      | "admin"
      | "blockJurisdiction"
      | "canTrade"
      | "complianceOfficers"
      | "getUserDailyVolume"
      | "getUserMonthlyVolume"
      | "isUserVerified"
      | "marketplace"
      | "protocolId"
      | "recordTrade"
      | "removeComplianceOfficer"
      | "resetVolumes"
      | "unblockJurisdiction"
      | "updateKYC"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComplianceOfficerAdded"
      | "ComplianceOfficerRemoved"
      | "JurisdictionBlocked"
      | "JurisdictionUnblocked"
      | "KYCUpdated"
      | "VolumeRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addComplianceOfficer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "blockJurisdiction",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canTrade",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "complianceOfficers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDailyVolume",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserMonthlyVolume",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isUserVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordTrade",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeComplianceOfficer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resetVolumes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unblockJurisdiction",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateKYC",
    values: [
      AddressLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "addComplianceOfficer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blockJurisdiction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "complianceOfficers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDailyVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserMonthlyVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isUserVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeComplianceOfficer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetVolumes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unblockJurisdiction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateKYC", data: BytesLike): Result;
}

export namespace ComplianceOfficerAddedEvent {
  export type InputTuple = [officer: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [officer: string, timestamp: bigint];
  export interface OutputObject {
    officer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceOfficerRemovedEvent {
  export type InputTuple = [officer: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [officer: string, timestamp: bigint];
  export interface OutputObject {
    officer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurisdictionBlockedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JurisdictionUnblockedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCUpdatedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VolumeRecordedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceModule extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceModule;
  waitForDeployment(): Promise<this>;

  interface: ComplianceModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addComplianceOfficer: TypedContractMethod<
    [officer: AddressLike],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  blockJurisdiction: TypedContractMethod<
    [jurisdictionCode: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  canTrade: TypedContractMethod<
    [user: AddressLike, tradeAmount: BytesLike],
    [string],
    "nonpayable"
  >;

  complianceOfficers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getUserDailyVolume: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getUserMonthlyVolume: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  isUserVerified: TypedContractMethod<[user: AddressLike], [string], "view">;

  marketplace: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  recordTrade: TypedContractMethod<
    [user: AddressLike, amount: BytesLike],
    [void],
    "nonpayable"
  >;

  removeComplianceOfficer: TypedContractMethod<
    [officer: AddressLike],
    [void],
    "nonpayable"
  >;

  resetVolumes: TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  unblockJurisdiction: TypedContractMethod<
    [jurisdictionCode: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  updateKYC: TypedContractMethod<
    [
      user: AddressLike,
      isVerified: BytesLike,
      isAccredited: BytesLike,
      riskLevel: BytesLike,
      jurisdiction: BytesLike,
      dailyLimit: BytesLike,
      monthlyLimit: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addComplianceOfficer"
  ): TypedContractMethod<[officer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "blockJurisdiction"
  ): TypedContractMethod<
    [jurisdictionCode: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canTrade"
  ): TypedContractMethod<
    [user: AddressLike, tradeAmount: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "complianceOfficers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getUserDailyVolume"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUserMonthlyVolume"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "isUserVerified"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "marketplace"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordTrade"
  ): TypedContractMethod<
    [user: AddressLike, amount: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeComplianceOfficer"
  ): TypedContractMethod<[officer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetVolumes"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unblockJurisdiction"
  ): TypedContractMethod<
    [jurisdictionCode: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateKYC"
  ): TypedContractMethod<
    [
      user: AddressLike,
      isVerified: BytesLike,
      isAccredited: BytesLike,
      riskLevel: BytesLike,
      jurisdiction: BytesLike,
      dailyLimit: BytesLike,
      monthlyLimit: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ComplianceOfficerAdded"
  ): TypedContractEvent<
    ComplianceOfficerAddedEvent.InputTuple,
    ComplianceOfficerAddedEvent.OutputTuple,
    ComplianceOfficerAddedEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceOfficerRemoved"
  ): TypedContractEvent<
    ComplianceOfficerRemovedEvent.InputTuple,
    ComplianceOfficerRemovedEvent.OutputTuple,
    ComplianceOfficerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "JurisdictionBlocked"
  ): TypedContractEvent<
    JurisdictionBlockedEvent.InputTuple,
    JurisdictionBlockedEvent.OutputTuple,
    JurisdictionBlockedEvent.OutputObject
  >;
  getEvent(
    key: "JurisdictionUnblocked"
  ): TypedContractEvent<
    JurisdictionUnblockedEvent.InputTuple,
    JurisdictionUnblockedEvent.OutputTuple,
    JurisdictionUnblockedEvent.OutputObject
  >;
  getEvent(
    key: "KYCUpdated"
  ): TypedContractEvent<
    KYCUpdatedEvent.InputTuple,
    KYCUpdatedEvent.OutputTuple,
    KYCUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VolumeRecorded"
  ): TypedContractEvent<
    VolumeRecordedEvent.InputTuple,
    VolumeRecordedEvent.OutputTuple,
    VolumeRecordedEvent.OutputObject
  >;

  filters: {
    "ComplianceOfficerAdded(address,uint256)": TypedContractEvent<
      ComplianceOfficerAddedEvent.InputTuple,
      ComplianceOfficerAddedEvent.OutputTuple,
      ComplianceOfficerAddedEvent.OutputObject
    >;
    ComplianceOfficerAdded: TypedContractEvent<
      ComplianceOfficerAddedEvent.InputTuple,
      ComplianceOfficerAddedEvent.OutputTuple,
      ComplianceOfficerAddedEvent.OutputObject
    >;

    "ComplianceOfficerRemoved(address,uint256)": TypedContractEvent<
      ComplianceOfficerRemovedEvent.InputTuple,
      ComplianceOfficerRemovedEvent.OutputTuple,
      ComplianceOfficerRemovedEvent.OutputObject
    >;
    ComplianceOfficerRemoved: TypedContractEvent<
      ComplianceOfficerRemovedEvent.InputTuple,
      ComplianceOfficerRemovedEvent.OutputTuple,
      ComplianceOfficerRemovedEvent.OutputObject
    >;

    "JurisdictionBlocked(uint256)": TypedContractEvent<
      JurisdictionBlockedEvent.InputTuple,
      JurisdictionBlockedEvent.OutputTuple,
      JurisdictionBlockedEvent.OutputObject
    >;
    JurisdictionBlocked: TypedContractEvent<
      JurisdictionBlockedEvent.InputTuple,
      JurisdictionBlockedEvent.OutputTuple,
      JurisdictionBlockedEvent.OutputObject
    >;

    "JurisdictionUnblocked(uint256)": TypedContractEvent<
      JurisdictionUnblockedEvent.InputTuple,
      JurisdictionUnblockedEvent.OutputTuple,
      JurisdictionUnblockedEvent.OutputObject
    >;
    JurisdictionUnblocked: TypedContractEvent<
      JurisdictionUnblockedEvent.InputTuple,
      JurisdictionUnblockedEvent.OutputTuple,
      JurisdictionUnblockedEvent.OutputObject
    >;

    "KYCUpdated(address,uint256)": TypedContractEvent<
      KYCUpdatedEvent.InputTuple,
      KYCUpdatedEvent.OutputTuple,
      KYCUpdatedEvent.OutputObject
    >;
    KYCUpdated: TypedContractEvent<
      KYCUpdatedEvent.InputTuple,
      KYCUpdatedEvent.OutputTuple,
      KYCUpdatedEvent.OutputObject
    >;

    "VolumeRecorded(address,uint256)": TypedContractEvent<
      VolumeRecordedEvent.InputTuple,
      VolumeRecordedEvent.OutputTuple,
      VolumeRecordedEvent.OutputObject
    >;
    VolumeRecorded: TypedContractEvent<
      VolumeRecordedEvent.InputTuple,
      VolumeRecordedEvent.OutputTuple,
      VolumeRecordedEvent.OutputObject
    >;
  };
}
