/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedOrderbookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assetOrderCounts"
      | "buyHeadIds"
      | "getAssetOrderCount"
      | "getBestBuyOrder"
      | "getBestSellOrder"
      | "getBuyOrders"
      | "getOrderDetails"
      | "getSellOrders"
      | "insertBuyOrder"
      | "insertSellOrder"
      | "marketplace"
      | "orderNodes"
      | "protocolId"
      | "removeBuyOrder"
      | "removeSellOrder"
      | "sellHeadIds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OrderInserted" | "OrderRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "assetOrderCounts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyHeadIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssetOrderCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBestBuyOrder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBestSellOrder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "insertBuyOrder",
    values: [BigNumberish, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "insertSellOrder",
    values: [BigNumberish, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marketplace",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orderNodes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeBuyOrder",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSellOrder",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sellHeadIds",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "assetOrderCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyHeadIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAssetOrderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBestBuyOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBestSellOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insertBuyOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insertSellOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "marketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orderNodes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeBuyOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSellOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellHeadIds",
    data: BytesLike
  ): Result;
}

export namespace OrderInsertedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    asset: AddressLike,
    isBuy: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    asset: string,
    isBuy: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    asset: string;
    isBuy: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderRemovedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    asset: AddressLike,
    isBuy: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    asset: string,
    isBuy: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    asset: string;
    isBuy: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedOrderbook extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedOrderbook;
  waitForDeployment(): Promise<this>;

  interface: EncryptedOrderbookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assetOrderCounts: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  buyHeadIds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getAssetOrderCount: TypedContractMethod<
    [asset: AddressLike],
    [bigint],
    "view"
  >;

  getBestBuyOrder: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  getBestSellOrder: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  getBuyOrders: TypedContractMethod<
    [asset: AddressLike, maxCount: BigNumberish],
    [bigint[]],
    "view"
  >;

  getOrderDetails: TypedContractMethod<
    [orderId: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        price: string;
        amount: string;
        timestamp: bigint;
        nextOrderId: bigint;
      }
    ],
    "view"
  >;

  getSellOrders: TypedContractMethod<
    [asset: AddressLike, maxCount: BigNumberish],
    [bigint[]],
    "view"
  >;

  insertBuyOrder: TypedContractMethod<
    [
      orderId: BigNumberish,
      asset: AddressLike,
      price: BytesLike,
      amount: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  insertSellOrder: TypedContractMethod<
    [
      orderId: BigNumberish,
      asset: AddressLike,
      price: BytesLike,
      amount: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  marketplace: TypedContractMethod<[], [string], "view">;

  orderNodes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean] & {
        orderId: bigint;
        price: string;
        amount: string;
        timestamp: bigint;
        nextOrderId: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  removeBuyOrder: TypedContractMethod<
    [orderId: BigNumberish, asset: AddressLike],
    [void],
    "nonpayable"
  >;

  removeSellOrder: TypedContractMethod<
    [orderId: BigNumberish, asset: AddressLike],
    [void],
    "nonpayable"
  >;

  sellHeadIds: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assetOrderCounts"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyHeadIds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAssetOrderCount"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBestBuyOrder"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBestSellOrder"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBuyOrders"
  ): TypedContractMethod<
    [asset: AddressLike, maxCount: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrderDetails"
  ): TypedContractMethod<
    [orderId: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        price: string;
        amount: string;
        timestamp: bigint;
        nextOrderId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellOrders"
  ): TypedContractMethod<
    [asset: AddressLike, maxCount: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "insertBuyOrder"
  ): TypedContractMethod<
    [
      orderId: BigNumberish,
      asset: AddressLike,
      price: BytesLike,
      amount: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "insertSellOrder"
  ): TypedContractMethod<
    [
      orderId: BigNumberish,
      asset: AddressLike,
      price: BytesLike,
      amount: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "marketplace"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "orderNodes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, boolean] & {
        orderId: bigint;
        price: string;
        amount: string;
        timestamp: bigint;
        nextOrderId: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeBuyOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish, asset: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeSellOrder"
  ): TypedContractMethod<
    [orderId: BigNumberish, asset: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sellHeadIds"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "OrderInserted"
  ): TypedContractEvent<
    OrderInsertedEvent.InputTuple,
    OrderInsertedEvent.OutputTuple,
    OrderInsertedEvent.OutputObject
  >;
  getEvent(
    key: "OrderRemoved"
  ): TypedContractEvent<
    OrderRemovedEvent.InputTuple,
    OrderRemovedEvent.OutputTuple,
    OrderRemovedEvent.OutputObject
  >;

  filters: {
    "OrderInserted(uint256,address,bool,uint256)": TypedContractEvent<
      OrderInsertedEvent.InputTuple,
      OrderInsertedEvent.OutputTuple,
      OrderInsertedEvent.OutputObject
    >;
    OrderInserted: TypedContractEvent<
      OrderInsertedEvent.InputTuple,
      OrderInsertedEvent.OutputTuple,
      OrderInsertedEvent.OutputObject
    >;

    "OrderRemoved(uint256,address,bool,uint256)": TypedContractEvent<
      OrderRemovedEvent.InputTuple,
      OrderRemovedEvent.OutputTuple,
      OrderRemovedEvent.OutputObject
    >;
    OrderRemoved: TypedContractEvent<
      OrderRemovedEvent.InputTuple,
      OrderRemovedEvent.OutputTuple,
      OrderRemovedEvent.OutputObject
    >;
  };
}
